import { type Module, inject } from 'langium'
import {
  createDefaultModule,
  createDefaultSharedModule,
  type DefaultSharedModuleContext,
  type LangiumServices,
  type LangiumSharedServices,
  type PartialLangiumServices,
} from 'langium/lsp'
import {
  ObjectOrientedCGeneratedModule,
  ObjectOrientedCGeneratedSharedModule,
} from './generated/module.js'
import {
  ObjectOrientedCValidator,
  registerValidationChecks,
} from './object-oriented-c-validator.js'
import type { OocConfig } from './diagnostics-config.js'
import { ConfigAwareDocumentValidator } from './diagnostics-config.js'
import { ObjectOrientedCSemanticTokenProvider } from './object-oriented-c-semantic-token-provider.js'
import { ObjectOrientedCHoverProvider } from './object-oriented-c-hover-provider.js'
import { ObjectOrientedCCompletionProvider } from './object-oriented-c-completion-provider.js'
import { ObjectOrientedCSignatureHelpProvider } from './object-oriented-c-signature-help-provider.js'
import { ObjectOrientedCDefinitionProvider } from './object-oriented-c-definition-provider.js'
import { ObjectOrientedCReferencesProvider } from './object-oriented-c-references-provider.js'

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ObjectOrientedCAddedServices = {
  validation: {
    ObjectOrientedCValidator: ObjectOrientedCValidator
  }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ObjectOrientedCServices = LangiumServices &
  ObjectOrientedCAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ObjectOrientedCModule: Module<
  ObjectOrientedCServices,
  PartialLangiumServices & ObjectOrientedCAddedServices
> = {
  validation: {
    ObjectOrientedCValidator: (services) =>
      new ObjectOrientedCValidator(services),
    DocumentValidator: (services) =>
      new ConfigAwareDocumentValidator(services),
  },
  lsp: {
    HoverProvider: (service) => new ObjectOrientedCHoverProvider(service),
    SemanticTokenProvider: (service) =>
      new ObjectOrientedCSemanticTokenProvider(service),
    // 代码自动补全
    CompletionProvider: (service) =>
      new ObjectOrientedCCompletionProvider(service),
    // 签名帮助
    SignatureHelp: (service) =>
      new ObjectOrientedCSignatureHelpProvider(service),
    // 跳转定义
    DefinitionProvider: (service) =>
      new ObjectOrientedCDefinitionProvider(service),
    // 查找引用
    ReferencesProvider: (services) =>
      new ObjectOrientedCReferencesProvider(services),
  },
}

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createObjectOrientedCServices(
  context: DefaultSharedModuleContext,
  config?: OocConfig,
): {
  shared: LangiumSharedServices
  ObjectOrientedC: ObjectOrientedCServices
} {
  const shared = inject(
    createDefaultSharedModule(context),
    ObjectOrientedCGeneratedSharedModule,
  )
  const ObjectOrientedC = inject(
    createDefaultModule({ shared }),
    ObjectOrientedCGeneratedModule,
    ObjectOrientedCModule,
  )
  shared.ServiceRegistry.register(ObjectOrientedC)
  registerValidationChecks(ObjectOrientedC, config)
  if (!context.connection) {
    // We don't run inside a language server
    // Therefore, initialize the configuration provider instantly
    shared.workspace.ConfigurationProvider.initialized({})
  }
  return { shared, ObjectOrientedC }
}
